import fs from "fs";
import path from "path";
import YAML from "yaml";
import RefParser from "@apidevtools/json-schema-ref-parser";
import { jsonSchemaToZod } from "json-schema-to-zod";

async function generate() {
  try {
    // Read openapi.yaml
    const specPath = path.join(process.cwd(), "openapi.yaml");
    const specContent = fs.readFileSync(specPath, "utf-8");
    const spec = YAML.parse(specContent);

    // Dereference all $ref
    const derefSpec = await RefParser.dereference(spec);

    // Extract schemas
    const schemas = derefSpec.components?.schemas || {};

    // Generate Zod code for each schema
    const zodCode = Object.entries(schemas).map(([name, schema]) => {
      const code = jsonSchemaToZod(schema as any, { module: "none" });
      return `export const ${name}Schema = ${code};`;
    });

    // Build output file
    const output = [
      "// AUTO-GENERATED by npm run generate",
      "// Do not edit manually — regenerate from openapi.yaml",
      "",
      'import { z } from "zod";',
      "",
      ...zodCode,
    ].join("\n");

    // Write to src/generated/schemas.ts
    const outDir = path.join(process.cwd(), "src", "generated");
    if (!fs.existsSync(outDir)) {
      fs.mkdirSync(outDir, { recursive: true });
    }

    const outPath = path.join(outDir, "schemas.ts");
    fs.writeFileSync(outPath, output);

    console.log(`✓ Generated ${outPath}`);
    console.log(`  - ${Object.keys(schemas).length} schemas exported`);
  } catch (error) {
    console.error("❌ Generation failed:", error);
    process.exit(1);
  }
}

generate();
